version: '3.8'

services:
  db:
    image: postgres:15
    container_name: secsafe-postgres
    environment:
      POSTGRES_USER: secadmin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: secsafe_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: secsafe-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
